var OPEN_WEATHER_KEY = process.env.OPEN_WEATHER_KEY ||'44dbb27c8c265c161323d4f7a8f250a6';
var OPEN_WEATHER_API =  process.env.OPEN_WEATHER_API || 'https://api.openweathermap.org/data/2.5';
var OPEN_WEATHER_API_DAY = process.env.OPEN_WEATHER_API_DAY || `${OPEN_WEATHER_API}/weather?`;
var OPEN_WEATHER_API_FORECAST = process.env.OPEN_WEATHER_API_FORECAST || `${OPEN_WEATHER_API}/forecast?`;
var CURRENT_TYPE = 'current';
var FORECAST_TYPE = 'forecast';

exports.OPEN_WEATHER_KEY = OPEN_WEATHER_KEY;
exports.OPEN_WEATHER_API_DAY = OPEN_WEATHER_API_DAY;
exports.OPEN_WEATHER_API_FORECAST = OPEN_WEATHER_API_FORECAST;
exports.CURRENT_TYPE = CURRENT_TYPE;
exports.FORECAST_TYPE = FORECAST_TYPE;
